global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'ecom_service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
#      - targets: ['192.168.11.117:8080']
      - targets: ['my-ecom-service:8081']
        labels:
          application: 'My ECOM Service Application'